# Generated by Django 2.2 on 2021-07-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yacht', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='liked_posts', to='yacht.User'),
        ),
    ]
